apiVersion: v2
name: argocd-config
description: Chart for ArgoCD
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: argo-cd
    version: 5.46.7
    repository: https://argoproj.github.io/argo-helm